image:
  repository: aksdemoacr20251027.azurecr.io/myapi
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress désactivé pour simplifier (on expose via LoadBalancer)
ingress:
  enabled: false
  className: ""
  hosts:
    - host: myapi.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
